version: '3.8'

services:

 database:
        image: mongo:latest
        container_name: mongo_metabase
        restart: always
        ports:
         - 27017:27017
        environment:
          MONGO_INITDB_ROOT_USERNAME: lappis
          MONGO_INITDB_ROOT_PASSWORD: lappis
          MONGO_INITDB_DATABASE: metabase 

 aplication:
        container_name: python_app
        image: python:3.8
        build:
            context: .
            dockerfile: dockerfile
        command: python src/main.py 
        command:  tail -f /dev/null
        volumes:
            - .:/app
        ports:
            - 5000:5000
        depends_on:
            - database
        links:
            - database

 postgressDb:
        image: postgres:latest
        container_name: postgresql_metabase
        restart: always
        environment:
            POSTGRES_DB: metabase
            POSTGRES_USER: lappis
            POSTGRES_PASSWORD: lappis
     

 metabasePart:
        image: metabase/metabase:latest
        container_name: metabase
        restart: always
        environment:
            MB_DB_TYPE: postgres
            MB_DB_DBNAME: metabase
            MB_DB_PORT: 5432
            MB_DB_USER: lappis
            MB_DB_PASS: lappis
            MB_DB_HOST: postgressDb
            MB_DB_FILE: /metabase-data/metabase.db
        depends_on:
            - postgressDb
        volumes:
            - .:/metabase
        ports:
            - 3000:3000