version: '3.8'

services:

  database:
    image: mongo:latest
    container_name: mongo_metabase
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: lappis
      MONGO_INITDB_ROOT_PASSWORD: lappis
      MONGO_INITDB_DATABASE: metabase 

  aplication:
    container_name: python_app
    image: python:3.8
    build:
      context: .
      dockerfile: dockerfile
    command: python src/main.py 
    command:  tail -f /dev/null
    volumes:
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - database
    links:
      - database

  meta:
    image: metabase/metabase:latest
    container_name: metabase
    restart: always
    depends_on:
      - database
    volumes:
      - .:/metabase
    ports:
      - "3000:3000"