version: '3.8'

services:
  database:
      image: mongo:latest
      container_name: dabase_mongo_db
      restart: always
      ports:
         - 27017:27017
      environment:
         MONGO_INITDB_ROOT_USERNAME: root
         MONGO_INITDB_ROOT_PASSWORD: example
         MONGO_INITDB_DATABASE: mongo_db 
      volumes:
      - mgdata:/data/mongo

volumes:
  mgdata:
    driver: local
 