name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install flake8 pytest-cov
      - name: Lint with flake8
        run: |
          flake8 --extend-ignore=E302,E101,E131,W191,W293,W292,W291,E201,E303,F401,E275,E305,E275,E701,E275,E701,F401,E251,E722,F401   --count --select=E9,F63,F7,F82 --exclude=*.pyc,*migrations* --show-source --statistics
          flake8 --extend-ignore=E302,E101,E131,W191,W293,W292,W291,E201,E303,F401,E275,E305,E275,E701,E275,E701,F401,E251,E722,F401  --count --max-complexity=10 --max-line-length=226 --exclude=*.pyc,*migrations* --statistics 
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test
        working-directory: ./tests
        run: |
          pip install pytest
          pytest --cov
